{"message":"ACL is required.","stack":"Error: ACL is required.\n    at SchemaController.validateRequiredColumns (/home/support/Documents/repositorios/catch-cep-api/node_modules/parse-server/lib/Controllers/SchemaController.js:1133:13)\n    at schemaPromise.then.schema (/home/support/Documents/repositorios/catch-cep-api/node_modules/parse-server/lib/Controllers/SchemaController.js:1285:19)\n    at <anonymous>\n    at process._tickDomainCallback (internal/process/next_tick.js:228:7)","code":111,"level":"error","timestamp":"2019-02-11T14:36:58.524Z"}
{"message":"ACL is required.","stack":"Error: ACL is required.\n    at SchemaController.validateRequiredColumns (/home/support/Documents/repositorios/catch-cep-api/node_modules/parse-server/lib/Controllers/SchemaController.js:1133:13)\n    at schemaPromise.then.schema (/home/support/Documents/repositorios/catch-cep-api/node_modules/parse-server/lib/Controllers/SchemaController.js:1285:19)\n    at <anonymous>\n    at process._tickDomainCallback (internal/process/next_tick.js:228:7)","code":111,"level":"error","timestamp":"2019-02-11T14:37:33.253Z"}
{"functionName":"test","error":{"message":"response.success is not a function","code":141},"params":{},"level":"error","message":"Failed running cloud function test for user undefined with:\n  Input: {}\n  Error: {\"message\":\"response.success is not a function\",\"code\":141}","timestamp":"2019-02-11T15:49:56.060Z"}
{"message":"response.success is not a function","stack":"Error: response.success is not a function\n    at error (/home/support/Documents/repositorios/catch-cep-api/node_modules/parse-server/lib/Routers/FunctionsRouter.js:121:16)\n    at <anonymous>","code":141,"level":"error","timestamp":"2019-02-11T15:49:56.073Z"}
{"functionName":"test","error":{"message":"response.success is not a function","code":141},"params":{},"level":"error","message":"Failed running cloud function test for user undefined with:\n  Input: {}\n  Error: {\"message\":\"response.success is not a function\",\"code\":141}","timestamp":"2019-02-11T15:50:24.623Z"}
{"message":"response.success is not a function","stack":"Error: response.success is not a function\n    at error (/home/support/Documents/repositorios/catch-cep-api/node_modules/parse-server/lib/Routers/FunctionsRouter.js:121:16)\n    at <anonymous>","code":141,"level":"error","timestamp":"2019-02-11T15:50:24.626Z"}
{"functionName":"test","error":{"message":"response.success is not a function","code":141},"params":{},"level":"error","message":"Failed running cloud function test for user undefined with:\n  Input: {}\n  Error: {\"message\":\"response.success is not a function\",\"code\":141}","timestamp":"2019-02-11T15:51:10.337Z"}
{"message":"response.success is not a function","stack":"Error: response.success is not a function\n    at error (/home/support/Documents/repositorios/catch-cep-api/node_modules/parse-server/lib/Routers/FunctionsRouter.js:121:16)\n    at <anonymous>","code":141,"level":"error","timestamp":"2019-02-11T15:51:10.340Z"}
{"functionName":"test","error":{"message":"response.success is not a function","code":141},"params":{},"level":"error","message":"Failed running cloud function test for user undefined with:\n  Input: {}\n  Error: {\"message\":\"response.success is not a function\",\"code\":141}","timestamp":"2019-02-11T15:54:11.847Z"}
{"message":"response.success is not a function","stack":"Error: response.success is not a function\n    at error (/home/support/Documents/repositorios/catch-cep-api/node_modules/parse-server/lib/Routers/FunctionsRouter.js:121:16)\n    at <anonymous>","code":141,"level":"error","timestamp":"2019-02-11T15:54:11.849Z"}
